### ISSUE TITLE
Resources referenced in CSS files aren't fetched with Host header set

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler-proxy#2]
Steps to reproduce: 
- Check out new version of bundler-proxy
- `npm install`
- Use standard `remaps.json` file
- Fetch with `curl 127.0.0.1:9008/?url=http://distributed.deflect.ca`
- Observe failed fetch - `socket hang up`, origin logs requests with absent Host header set
- Use `spoofHeaders` to set `Host` Header: `"Host": "deflect.ca"`
- Repeat fetch test, test is successful.

**Comment by chaoticsmol** [comment]
This isn't quite the same bug reported in https://github.com/equalitie/bundler/issues/16  is it?

If I'm understanding this correctly, you're saying that the request to `http://distributed.deflect.ca` **should not** fail if no Host header is set?

I've copied the bundler-proxy configs and server code into the test directory for my copy of the bundler library and did the following with an _empty_ `remaps.json` file:
1. Start the proxy server (modified to print request headers and requested url), output below.
2. Ran `curl http://127.0.0.1:9008\?url\=http://distributed.deflect.ca`

Output from the server after step 2:

```
Got request with req.url = /?url=http://distributed.deflect.ca
Headers
{ 'user-agent': 'curl/7.37.1',
  host: '127.0.0.1:9008',
  accept: '*/*' }
Returning bundle for url http://distributed.deflect.ca
```

CURL also reports that the page was retrieved correctly and the HTML it prints definitely looks like the right stuff.

I suspect this has already been fixed in the bundler library. I'll try republishing and then repeating your steps exactly with an updated bundler-proxy.

**Comment by chaoticsmol** [comment]
**Update**

I have republished the bundler library and also managed to reproduce the original bug.

Noted that the Host header has to be overwritten for both the original request as well as requests for all resources (resourceRequest) for it to work.

**Comment by chaoticsmol** [comment]
I've pushed some code that will set the Host header in a request to the domain of the site requested (i.e. for distributed.deflect.ca, Host is set to deflect.ca).
Check it out here: https://github.com/equalitie/bundler-proxy/commit/8c80f9ef3a00f2832186b4fc0ebad19bed0faecf

I removed the entry in `spoofHeaders` explicitly setting the Host (for every request) to deflect.ca and also removed the remapping entry `'distributed.deflect.ca': 'deflect.ca'` from `remaps.json` in https://github.com/equalitie/bundler-proxy/commit/0eb3989a52db8785fe193bdfa245e0819afe4197 .

Now when I run the proxy server and then run `curl 127.0.0.1:9008/?url=http://distributed.deflect.ca` I get the following output:

``` html
<HTML>
<HEAD>
<TITLE>Access Denied</TITLE>
</HEAD>

<BODY BGCOLOR="white" FGCOLOR="black">
<H1>Access Denied</H1>
<HR>

<FONT FACE="Helvetica,Arial"><B>
Description: You are not allowed to access the document you requested.
</B></FONT>
<HR>
</BODY>
```

I guess this is better than having an error occur and you can probably figure out why this response is being served instead of the page you want.

**Comment by nosmo** [comment]
This was fixed by your changes/our discussions on IRC a while ago :)
